electronicsInventoryApp/urls.py
from django.contrib import admin
from django.urls import include, path

admin.site.site_header  =  "Electronics Lab"  
admin.site.site_title  =  "Electronics Lab Admin Portal"
admin.site.index_title  =  "Welcome to Electronics Lab Admin Portal"

urlpatterns = [
    path('', include('mainpage.urls')),
    path('admin/', admin.site.urls),
]

from django.conf.urls import handler400, handler403, handler404, handler500


# Customizing the built error pages
handler404 = 'mainpage.views.error_404'
handler500 = 'mainpage.views.error_500'
handler403 = 'mainpage.views.error_403'
handler400 = 'mainpage.views.error_400'

mainpage/urls.py
from django.urls import path

from . import views

app_name = 'mainpage'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path("search/",views.SearchResultsView.as_view(), name="search"),
    path("datasheets/<str:part>", views.datasheet, name="datasheet"),
    path("update_item/", views.updateItem, name="update_item"),
    path("shoppingCart/", views.ShoppingBasketView.as_view(), name="shoppingCart"),
    path("download_pdf", views.download_pdf, name="download_pdf"),
]

mainpage/models.py
import datetime

from django.db import models
from django.utils import timezone


class MAIN_LINKS(models.Model):
    
    main_name = models.CharField(max_length=200)

    def __str__(self):
        return self.main_name
    def reload(self):
        new_self = self.__class__.objects.get(pk=self.pk)
        self.__dict__.update(new_self.__dict__)

class TOP_BAR_LINKS(models.Model):

    main = models.ForeignKey(MAIN_LINKS, on_delete=models.CASCADE)
    top_bar_name = models.CharField(max_length=200)

    def __str__(self):
        return self.top_bar_name
    
    
class Storage(models.Model):
    room = models.CharField(primary_key=True, max_length=32, db_collation='utf8mb3_general_ci',blank = False)
    longname = models.CharField(max_length=32, db_collation='utf8mb3_general_ci')
    shortname = models.CharField(max_length=32, db_collation='utf8mb3_general_ci')
    responsible_person = models.CharField(max_length=32,blank = False)
    title_en = models.CharField(max_length=32, db_collation='utf8mb3_general_ci',blank = False)
    title_de = models.CharField(max_length=32, db_collation='utf8mb3_general_ci',blank = False)

    class Meta:
        managed = False
        db_table = 'storage'
    
    def __str__(self):
        return self.room


class Categories(models.Model):
    name = models.CharField(primary_key=True, max_length=32, db_collation='utf8mb3_general_ci',blank = False)

    class Meta:
        managed = False
        db_table = 'categories'

    def __str__(self):
        return self.name

class Electronicparts(models.Model):
    price = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, default=0)
    category = models.ForeignKey(Categories, models.DO_NOTHING, db_column='category',blank = False)
    part = models.CharField(max_length=256, db_collation='utf8mb3_general_ci',blank = False)
    datasheet = models.FileField()
    room_num = models.ForeignKey('Storage', models.DO_NOTHING, db_column='room_num',blank = False)
    box_num = models.IntegerField(blank=True, null=True)
    reichelt_name = models.CharField(max_length=32, db_collation='utf8mb3_general_ci', blank=True, null=True)
    reichelt_num = models.CharField(max_length=32, db_collation='utf8mb3_general_ci', blank=True, null=True)
    link_reichelt = models.CharField(max_length=128, db_collation='utf8mb3_general_ci', blank=True, null=True)
    link_conrad = models.CharField(max_length=128, db_collation='utf8mb3_general_ci', blank=True, null=True)
    link_voelkner = models.CharField(max_length=128, db_collation='utf8mb3_general_ci', blank=True, null=True)
    link_farnell = models.CharField(max_length=128, db_collation='utf8mb3_general_ci', blank=True, null=True)
    link_rs = models.CharField(max_length=128, db_collation='utf8mb3_general_ci', blank=True, null=True)
    link_mouser = models.CharField(max_length=128, db_collation='utf8mb3_general_ci', blank=True, null=True)
    link_digikey = models.CharField(max_length=128, db_collation='utf8mb3_general_ci', blank=True, null=True)
    link_other = models.CharField(max_length=128, db_collation='utf8mb3_general_ci', blank=True, null=True)
    remainder = models.IntegerField(blank = True, null = True, default=0)
    available = models.IntegerField(blank = True, null = True, default= 0)
    date_added = models.DateTimeField()
    id = models.BigAutoField(primary_key=True)
    compartment = models.CharField(max_length=32, db_collation='utf8mb3_general_ci', blank=True, null=True)
    search_fields = ['part', 'compartment','category']

    class Meta:
        managed = False
        db_table = 'electronicparts'
    
    def __str__(self):
        return self.part

class Datasheet(models.Model):

    datasheet = models.FileField()

    def __str__(self):
        return self.datasheet.name

class Mail (models.Model):
    mail = models.EmailField()
    send_to_this = models.BooleanField(default=False)
    def __str__(self):
        return self.mail

mainpage/views.py
from django.views import generic
from django.db.models import Q

from django.http import FileResponse, JsonResponse,HttpResponseBadRequest
import os
import json
from django.views.decorators.csrf import csrf_exempt
from django.shortcuts import render

from collections import defaultdict
from .models import MAIN_LINKS, TOP_BAR_LINKS, Electronicparts, Storage, Categories

import io
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm 


top_bar_quick_links ={}
cart_items = defaultdict(list)

number_of_items_in_cart = len(cart_items)

def refresh_top_bar_quick_links():
    for main_link in MAIN_LINKS.objects.all():
        top_bar_quick_links[main_link.main_name] = []
        for top_bar_link in TOP_BAR_LINKS.objects.filter(main=main_link):
            top_bar_quick_links[main_link.main_name].append(top_bar_link.top_bar_name)



content = [Electronicparts.objects.all().order_by('category'), top_bar_quick_links, Storage.objects.all(), Categories.objects.all(),number_of_items_in_cart]

class IndexView(generic.ListView):
    model = Electronicparts
    template_name = './mainpage/index.html'
    context_object_name = 'content'
    content_class = content
    def get_queryset(self):

        #object = Electronicparts.objects.filter(category = Categories.objects.first())

        self.content_class[0] = Electronicparts.objects.all().order_by('category')[:50]

        if self.request.method == "POST":
            pass
        try:
            self.content_class[4] = len(set(json.loads(self.request.COOKIES['cart'])))
        except:
            self.content_class[4] = 0
        #print("len",self.content_class[4])
        return self.content_class
                

        




class SearchResultsView(generic.ListView):
    model = Electronicparts
    template_name = './mainpage/search.html'
    context_object_name = 'content'
    content_class = list(content)


    def get_queryset(self):

        query = self.request.GET.get("q")
        object_list = Electronicparts.objects.filter(
            Q(part__icontains=query) | Q(category__name__icontains=query) | Q(room_num__room__icontains=query) 
        )
        if self.request.method == "POST":
            pass
        self.content_class[0] = object_list.order_by('category')
        try:
            self.content_class[4] = len(set(json.loads(self.request.COOKIES['cart'])))
        except:
            self.content_class[4] = 0

        #print("len",self.content_class[4])
        return self.content_class

class ShoppingBasketView(generic.ListView):

    model = Electronicparts
    template_name = './mainpage/shoppingCart.html'
    context_object_name = 'content'
    content_class = content

    def get_queryset(self):

        if self.request.method == "POST":
            pass
        try:
            ids = list(set(json.loads(self.request.COOKIES['cart'])))
            self.content_class[0] = Electronicparts.objects.filter(id__in=ids).order_by('category')
        except:
            self.content_class[0] = 0

        return self.content_class
        





def datasheet(request,part):
    
    filepath = os.path.join( f"./datasheets/{part}")
    return FileResponse(open(filepath, 'rb'), content_type='application/pdf')





@csrf_exempt
def updateItem(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    #print('Action:', action)
    #print('Product:', productId)
    try:
        cart_items:list = list(set(json.loads(request.COOKIES['cart'])))
        
    except:
        cart_items = []
    #print("Before:",cart_items)

    if action == 'add':
        cart_items.append(productId)
    elif action == 'remove':
        cart_items.remove(productId)

    content[4] = len(cart_items)
    #print("After:",cart_items)
    
    response = JsonResponse("Item was added", safe=False)
    response.set_cookie("cart",json.dumps(cart_items,), max_age=5000);

    return response

def download_pdf(request):

    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4,bottomup=0)
    
    textob = c.beginText()
    textob.setTextOrigin(1*cm, 1*cm)
    textob.setFont("Helvetica", 14)

    cart_items:list = list(set(json.loads(request.COOKIES['cart'])))
    parts = Electronicparts.objects.filter(id__in=cart_items).order_by('category')

    for part in parts:
        textob.textLine(f"Part Name: {part.part}")
        textob.textLine(f"Part Category: {part.category}")
        textob.textLine(f"Part Room: {part.room_num}")
        textob.textLine(f"Part Box Number: {part.box_num}")
        textob.textLine(f"Part Price: {part.price}")
        textob.textLine(f"Part Compartment: {part.compartment}")
        
        textob.textLine("="*50)

    c.drawText(textob)
    c.showPage()
    c.save()
    buf.seek(0)

    return FileResponse(buf, as_attachment=True, filename='shopping_cart.pdf')




    

from django.shortcuts import render


def error_404(request, exception):
    return render(request, 'mainpage/404.html')



def error_500(request, *args, **argv):
    return render(request, 'mainpage/500.html', status=500)

        
def error_403(request, exception):

        return render(request,'mainpage/403.html')

def error_400(request,  exception):
        return HttpResponseBadRequest('Bad Request!')

mainpage/templates/mainpage/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Electronics Lab inventory</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'mainpage/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css" />
    <link href="https://use.fontawesome.com/releases/v5.0.1/css/all.css" rel="stylesheet">

    {% load bootstrap5 %}
    {% bootstrap_css %}
    
</head>
<body>
    <div class="topbar">
        <div class = "logodiv"><a href="/"><img src="https://www.hochschule-rhein-waal.de/sites/default/themes/at_hrw/logo.png" alt="" class="logo"></a></div>
        <div class="navbar">
            
            <a href="/">Home</a>
            <a href="https://dokuwiki.hsrw.org/doku.php?id=ee:labs">About the Labs</a>
            <a href="https://dokuwiki.hsrw.org/doku.php?id=start">Wiki page</a>
            <a href="/admin">Admin</a>
            

            <form action="{% url 'mainpage:search' %}" method="get">
                
                <input  name="q" type="text" placeholder="Search..." id="myInput" autocomplete="off">
            </form>

            <a href="/shoppingCart">

                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                <span class="total-count">{{content.4}}</span>
            </a>
        
        </div>
       
    </div>
    <div class="viewport">
        <div class="sidenav">
           
                
            <div class="dropdown">
                <button onclick="catFilter()" class="dropbtn">Filter By Category</button>
                <div id="catFilter" class="dropdown-content">
                    <form action="{% url 'mainpage:search' %}" method="get">
                        <input name="q" type="text" placeholder="Search..."id="myInput">
                    </form>
                    {% for item in content.3 %}
    
                        <a href="/search/?q={{item}}">{{ item}}</a>
    
                    {% endfor %}
                    
                </div>
                <button onclick="roomFilter()" class="dropbtn">Filter By Room</button>
                <div id="roomFilter" class="dropdown-content">
                    <form action="{% url 'mainpage:search' %}" method="get">
                        <input name="q" type="text" placeholder="Search..."id="myInput">
                    </form>
                    {% for category in content.2 %}
                        <a href="/search/?q={{category}}">{{category}}</a>
                    {% endfor %}
                    
                </div>
              

                

            </div>
                         
            
        </div>
        <div class="content">
            <table>
                <tr>
                <th>Add to cart</th>
                  <th>Part</th>
                  <th>Category</th>
                  <th>Datasheet</th>
                  <!--<th>Price</th>-->
                  <th>Box Number</th>
                  <th>Room Number</th>
                  
                  <th>Where to buy</th>
                  
                </tr>
                {% for item in content.0 %}
                    <tr>
                        <td>
                            <button data-product = "{{item.id}}" data-action="add" type="submit" class="update-cart"> <i class="fa fa-shopping-cart" aria-hidden="true"></i></button>
                        </td>

                        <td>{{ item.part }}</td>
                        <td>{{ item.category }}</td>
                        <!--<td>{{ item.price }}</td>-->
                        {% if item.datasheet.name %}
                            <td><a target="_blank" rel="noopener" href="/datasheets/{{item.datasheet.name}}"><i class="fa fa-file" aria-hidden="true" style="color:red"></i></a></td>
                        {% else %}
                            <td><i class="fa fa-file" aria-hidden="true" style="color:gray"></i></td>
                        {% endif %}
                        <td>{{ item.box_num }}</td>
                        <td>{{ item.room_num }}</td>
                        <td>
                            {% if item.link_mouser %}
                                <a target="_blank" rel="noopener" href="{{item.link_mouser}}"><img src="https://www.mouser.de/favicon.ico" alt="link_mouser"></a>
                            {% endif %}

                            {% if item.link_reichelt %}
                                <a target="_blank" rel="noopener" href="{{item.link_reichelt}}"><img src="https://www.reichelt.de/favicon.ico" alt="link_reichelt"></a>
                            {% endif %}

                            {% if item.link_conrad %}
                                <a target="_blank" rel="noopener" href="{{item.link_conrad}}"><img src="https://www.conrad.de/favicon.ico" alt="link_conrad"></a>
                            {% endif %}

                            {% if item.link_voelkner %}
                                <a target="_blank" rel="noopener"href="{{item.link_voelkner}}"><img height="16" width="16" src='http://www.google.com/s2/favicons?domain={{item.link_voelkner}}' /></a>
                            {% endif %}

                            {% if item.link_farnell %}
                                <a target="_blank" rel="noopener" href="{{item.link_farnell}}"><img src="https://de.farnell.com/favicon.ico" alt="link_farnell"></a>
                            {% endif %}

                            {% if item.link_rs %}
                                <a  target="_blank" rel="noopener"href="{{item.link_rs}}"><img src="https://de.rs-online.com/favicon.ico" alt="link_rs"></a>
                            {% endif %}

                            {% if item.link_digikey %}
                                <a target="_blank" rel="noopener" href="{{item.link_digikey}}"><img src="https://www.digikey.de/favicon.ico" alt="link_digikey"></a>
                            {% endif %}

                            {% if item.link_other %}
                                <a target="_blank" rel="noopener" href="{{item.link_other}}"><img height="16" width="16" src='http://www.google.com/s2/favicons?domain={{item.link_other}}' /></a>
                            {% endif %}
                            
                            {% if  not item.link_other and  not item.link_digikey and not item.link_rs and not item.link_farnell and not item.link_voelkner and not item.link_conrad  and not item.link_reichelt and not item.link_mouser %}
                                {% if not item.reminder %}
                                <i class="fa fa-ban" aria-hidden="true" style="color:gray"></i>   
                                {% else %}
                                <i class="fa fa-shopping-cart" aria-hidden="true" style="color:gray"></i>
                                {% endif %}
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
              </table>
        </div>
    </div>


    <script>
        /* When the user clicks on the button,
        toggle between hiding and showing the dropdown content */
        function roomFilter() {
          document.getElementById("roomFilter").classList.toggle("show");
          document.getElementById("catFilter").classList.remove("show");
        }
        function catFilter() {
          document.getElementById("catFilter").classList.toggle("show")[1];
          document.getElementById("roomFilter").classList.remove("show");
        }

        function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getToken('csrftoken');
        
    </script>

    <script src="{% static 'mainpage/cart.js' %}"></script>
</body>
</html>

mainpage/templates/mainpage/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Electronics Lab inventory</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'mainpage/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css" />
    <link href="https://use.fontawesome.com/releases/v5.0.1/css/all.css" rel="stylesheet">

    {% load bootstrap5 %}
    {% bootstrap_css %}
    
</head>
<body>
    <div class="topbar">
        <div class = "logodiv"><a href="/"><img src="https://www.hochschule-rhein-waal.de/sites/default/themes/at_hrw/logo.png" alt="" class="logo"></a></div>
        <div class="navbar">
            <a href="/">Home</a>
            <a href="https://dokuwiki.hsrw.org/doku.php?id=ee:labs">About the Labs</a>
            <a href="https://dokuwiki.hsrw.org/doku.php?id=start">Wiki page</a>
            <a href="/admin">Admin</a>
            
            <form action="{% url 'mainpage:search' %}" method="get">
                <input  name="q" type="text" placeholder="Search..." id="myInput" autocomplete="off">
            </form>
            <a href="/shoppingCart">

                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                <span class="total-count">{{content.4}}</span>
            </a>

        </div>
        
    </div>
    <div class="viewport">
        <div class="sidenav">
            <div class="dropdown">
                <button onclick="catFilter()" class="dropbtn">Filter By Category</button>
                <div id="catFilter" class="dropdown-content">
                    <form action="{% url 'mainpage:search' %}" method="get">
                        <input name="q" type="text" placeholder="Search..."id="myInput">
                    </form>
                    {% for category in content.3 %}
    
                        <a href="/search/?q={{category}}">{{category}}</a>
    
                    {% endfor %}
                    
                </div>
                <button onclick="roomFilter()" class="dropbtn">Filter By Room</button>
                <div id="roomFilter" class="dropdown-content">
                    <form action="{% url 'mainpage:search' %}" method="get">
                        <input name="q" type="text" placeholder="Search..."id="myInput">
                    </form>
                    {% for category in content.2 %}
                    <a href="/search/?q={{ category}}">{{ category}}</a>
                    {% endfor %}
                    
                </div>
                
            </div>
        </div>
        <div class="content">
            <table>
                <tr>
                  <th>Add to cart</th>
                  <th>Part</th>
                  <th>Category</th>
                  <th>Datasheet</th>
                  <!--<th>Price</th>-->
                  <th>Box Number</th>
                  <th>Room Number</th>
                  
                  <th>Where to buy</th>
                  
                </tr>
                {% for item in content.0 %}
                    <tr>
                        <td>
                            <button data-product = "{{item.id}}" data-action="add" type="submit" class="update-cart"> <i class="fa fa-shopping-cart" aria-hidden="true"></i></button>
                        </td>
                        <td>{{ item.part }}</td>
                        <td>{{ item.category }}</td>
                        <!--<td>{{ item.price }}</td>-->
                        {% if item.datasheet.name %}
                            <td><a target="_blank" rel="noopener" href="/datasheets/{{item.datasheet.name}}"><i class="fa fa-file" aria-hidden="true" style="color:red"></i></a></td>
                        {% else %}
                            <td><i class="fa fa-file" aria-hidden="true" style="color:gray"></i></td>
                        {% endif %}
                        <td>{{ item.box_num }}</td>
                        <td>{{ item.room_num }}</td>
                        <td>
                            {% if item.link_mouser %}
                                <a target="_blank" rel="noopener" href="{{item.link_mouser}}"><img src="https://www.mouser.de/favicon.ico" alt="link_mouser"></a>
                            {% endif %}

                            {% if item.link_reichelt %}
                                <a target="_blank" rel="noopener" href="{{item.link_reichelt}}"><img src="https://www.reichelt.de/favicon.ico" alt="link_reichelt"></a>
                            {% endif %}

                            {% if item.link_conrad %}
                                <a target="_blank" rel="noopener"href="{{item.link_conrad}}"><img src="https://www.conrad.de/favicon.ico" alt="link_conrad"></a>
                            {% endif %}

                            {% if item.link_voelkner %}
                            <a target="_blank" rel="noopener" href="{{item.link_voelkner}}"><img height="16" width="16" src='http://www.google.com/s2/favicons?domain={{item.link_voelkner}}' /></a>
                            {% endif %}

                            {% if item.link_farnell %}
                                <a target="_blank" rel="noopener" href="{{item.link_farnell}}"><img src="https://de.farnell.com/favicon.ico" alt="link_farnell"></a>
                            {% endif %}

                            {% if item.link_rs %}
                                <a target="_blank" rel="noopener" href="{{item.link_rs}}"><img src="https://de.rs-online.com/favicon.ico" alt="link_rs"></a>
                            {% endif %}

                            {% if item.link_digikey %}
                                <a target="_blank" rel="noopener" href="{{item.link_digikey}}"><img src="https://www.digikey.de/favicon.ico" alt="link_digikey"></a>
                            {% endif %}

                            {% if item.link_other %}
                            <a target="_blank" rel="noopener" href="{{item.link_other}}"><img height="16" width="16" src='http://www.google.com/s2/favicons?domain={{item.link_other}}' /></a>
                            {% endif %}
                            
                            {% if  not item.link_other and  not item.link_digikey and not item.link_rs and not item.link_farnell and not item.link_voelkner and not item.link_conrad  and not item.link_reichelt and not item.link_mouser %}
                                {% if not item.reminder %}
                                <i class="fa fa-ban" aria-hidden="true"style="color:gray"></i>   
                                {% else %}
                                <i class="fa fa-shopping-cart" aria-hidden="true" style="color:gray"></i>
                                {% endif %}
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
              </table>
        </div>
    </div>

    <script>
        /* When the user clicks on the button,
        toggle between hiding and showing the dropdown content */
        function roomFilter() {
          document.getElementById("roomFilter").classList.toggle("show");
          document.getElementById("catFilter").classList.remove("show");
        }
        function catFilter() {
          document.getElementById("catFilter").classList.toggle("show")[1];
          document.getElementById("roomFilter").classList.remove("show");
        }
        function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getToken('csrftoken');
     </script>

    <script src="{% static 'mainpage/cart.js' %}"></script>
</body>
</html>